### ISSUE TITLE
希望把算法整理到hlsl文件里面

### ISSUE THREAD

**Issue by Yogioo** [AnCG7/URPShaderCodeSample#1]
仓库内容非常不错, 不过实际项目使用大部分都是用hlsl, 实际shader文件里面只需要include调用方法即可, 所以有可能的话能不能整合到hlsl内部, 分模块

**Comment by AnCG7** [comment]
多谢夸奖与支持，这个问题有个小故事
一开始的时候我想研究一下如何将pbr和卡通渲染结合在一起，我在想理论上就是直接用现有的公式，然后想办法用一张ramp纹理映射一下，但我去尝试的时候，我发现这里要学的东西非常多，因为我的本职并不是引擎和TA。但是当我自学时发现，unity的shader相关的东西感觉破碎感特别强，我觉得并不复杂的东西，在unity里却被封了很多层和一堆的宏，这虽然方便项目使用，但大大增加了学习难度，所以我打算把unity的库拆了，把pbr以及相关的东西拆了整理一个库出来。为此我打算尝试看懂unity的shader的内容都是什么，我可不想漏了什么代码。这也意味着我至少需要大概理解一些算法相关的东西。在恶补式学习的过程中，我发现了一件更加折麽的问题，那就是网上资料的混乱，这使我一开始只是整理一个库的目标发生了转折，我更需要一个备忘录或者一个完整的教程。所以该仓库正如我在readme写的一样，该仓库的shader文件会有大面积的注释，其目的是我自己的备忘录以及分享给和我有同样问题的同学做为参考。更偏向教程和博客或者demo的范畴。所以我并不打算在该仓库整理成项目使用的库的形式，但我会尽量保证将重要的代码写在文件的函数里，而不是散在顶点和像素着色器函数中，可以方便的复制函数稍加修改就可以在项目使用，这也算一个折中吧
生活愉快～

**Comment by Yogioo** [comment]
> 多谢夸奖与支持，这个问题有个小故事 一开始的时候我想研究一下如何将pbr和卡通渲染结合在一起，我在想理论上就是直接用现有的公式，然后想办法用一张ramp纹理映射一下，但我去尝试的时候，我发现这里要学的东西非常多，因为我的本职并不是引擎和TA。但是当我自学时发现，unity的shader相关的东西感觉破碎感特别强，我觉得并不复杂的东西，在unity里却被封了很多层和一堆的宏，这虽然方便项目使用，但大大增加了学习难度，所以我打算把unity的库拆了，把pbr以及相关的东西拆了整理一个库出来。为此我打算尝试看懂unity的shader的内容都是什么，我可不想漏了什么代码。这也意味着我至少需要大概理解一些算法相关的东西。在恶补式学习的过程中，我发现了一件更加折麽的问题，那就是网上资料的混乱，这使我一开始只是整理一个库的目标发生了转折，我更需要一个备忘录或者一个完整的教程。所以该仓库正如我在readme写的一样，该仓库的shader文件会有大面积的注释，其目的是我自己的备忘录以及分享给和我有同样问题的同学做为参考。更偏向教程和博客或者demo的范畴。所以我并不打算在该仓库整理成项目使用的库的形式，但我会尽量保证将重要的代码写在文件的函数里，而不是散在顶点和像素着色器函数中，可以方便的复制函数稍加修改就可以在项目使用，这也算一个折中吧 生活愉快～

你说的对, 如果是一个学习和备用项目的话非常赞, 减少跳转是一个更容易理解的思路, 我是工程向思维去考虑的, 没有想到这一层, 我非常喜欢这个项目而且分享给了其他人 ヾ(◍°∇°◍)ﾉﾞ.
